# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: tweak-challenge

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs10.x
  region: sa-east-1
  stackName: tweakImageUploader
  iamRoleStatements:
    - Effect: "Allow"
      Action: 
        - "logs:CreateLogGroup"
        - "logs:CreateLogStream"
        - "logs:PutLogEvents"
      Resource:
        - "arn:aws:logs:*:*:*"
    - Effect: "Allow"
      Action:
        - "s3:PutObject" 
      Resource: 
        - "arn:aws:s3:::tweak-challenge-images/*"

# The `functions` block defines what code to deploy
functions:
  PostImage:
    handler: endpoints/images/upload.handler
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: images
          method: post
          cors: true
          integration: lambda
          request:
            passThrough: WHEN_NO_TEMPLATES
            template:
              image/jpg: '{ "content": "$input.body" }'
              image/jpeg: '{ "content": "$input.body" }'
              image/png: '{ "content": "$input.body" }'
    environment:
      Bucket: tweak-challenge-images

resources:
  Resources:
    StorageBucket:
      Type: "AWS::S3::Bucket"
      Properties:
        BucketName: tweak-challenge-images